package com.daidai.panel.core.network

object ApiEndpoints {
    const val baseApi = "/api"
    const val baseApiV1 = "/api/v1"

    // Auth
    const val AUTH_CHECK_INIT = "$baseApi/auth/check-init"
    const val AUTH_INIT = "$baseApi/auth/init"
    const val AUTH_LOGIN = "$baseApi/auth/login"
    const val AUTH_LOGOUT = "$baseApi/auth/logout"
    const val AUTH_REFRESH = "$baseApi/auth/refresh"
    const val AUTH_USER = "$baseApi/auth/user"
    const val AUTH_PASSWORD = "$baseApi/auth/password"
    const val AUTH_CAPTCHA_CONFIG = "$baseApi/auth/captcha-config"

    // System
    const val SYSTEM_HEALTH = "$baseApiV1/health"
    const val SYSTEM_VERSION = "$baseApi/system/version"
    const val SYSTEM_INFO = "$baseApi/system/info"
    const val SYSTEM_DASHBOARD = "$baseApi/system/dashboard"
    const val SYSTEM_STATS = "$baseApi/system/stats"
    const val SYSTEM_CHECK_UPDATE = "$baseApi/system/check-update"
    const val SYSTEM_SETTINGS = "$baseApi/system/settings"
    const val SYSTEM_LOG = "$baseApi/system/log"
    const val SYSTEM_SPONSORS = "$baseApi/system/sponsors"
    const val SYSTEM_BACKUP = "$baseApi/system/backup"
    const val SYSTEM_BACKUPS = "$baseApi/system/backups"
    const val SYSTEM_BACKUP_UPLOAD = "$baseApi/system/backup/upload"
    const val SYSTEM_BACKUP_DOWNLOAD = "$baseApi/system/backup/download"
    const val SYSTEM_RESTORE = "$baseApi/system/restore"
    const val SYSTEM_RESTORE_PROGRESS = "$baseApi/system/restore/progress"

    // Tasks
    const val TASKS = "$baseApi/tasks"
    fun taskById(id: Int): String = "$baseApi/tasks/$id"
    fun taskRun(id: Int): String = "$baseApi/tasks/$id/run"
    fun taskStop(id: Int): String = "$baseApi/tasks/$id/stop"
    fun taskEnable(id: Int): String = "$baseApi/tasks/$id/enable"
    fun taskDisable(id: Int): String = "$baseApi/tasks/$id/disable"
    fun taskPin(id: Int): String = "$baseApi/tasks/$id/pin"
    fun taskUnpin(id: Int): String = "$baseApi/tasks/$id/unpin"
    fun taskCopy(id: Int): String = "$baseApi/tasks/$id/copy"
    fun taskLatestLog(id: Int): String = "$baseApi/tasks/$id/latest-log"
    fun taskLiveLogs(id: Int): String = "$baseApi/tasks/$id/live-logs"
    fun taskLogFiles(id: Int): String = "$baseApi/tasks/$id/log-files"
    fun taskStats(id: Int): String = "$baseApi/tasks/$id/stats"
    const val TASKS_BATCH = "$baseApi/tasks/batch"
    const val TASKS_CLEAN_LOGS = "$baseApi/tasks/clean-logs"
    const val TASKS_EXPORT = "$baseApi/tasks/export"
    const val TASKS_IMPORT = "$baseApi/tasks/import"
    const val TASKS_CRON_PARSE = "$baseApi/tasks/cron-parse"
    const val TASKS_CRON_TEMPLATES = "$baseApi/tasks/cron-templates"
    const val TASKS_NOTIFICATION_CHANNELS = "$baseApi/tasks/notification-channels"

    // Logs
    const val LOGS = "$baseApi/logs"
    fun logById(id: Int): String = "$baseApi/logs/$id"
    fun logStream(id: Int): String = "$baseApiV1/logs/$id/stream"
    const val LOGS_BATCH_DELETE = "$baseApi/logs/batch-delete"
    const val LOGS_CLEAN = "$baseApi/logs/clean"

    // Scripts
    const val SCRIPTS_TREE = "$baseApi/scripts/tree"
    const val SCRIPTS_CONTENT = "$baseApi/scripts/content"
    const val SCRIPTS_DOWNLOAD = "$baseApi/scripts/download"
    const val SCRIPTS_UPLOAD = "$baseApi/scripts/upload"
    const val SCRIPTS_DIRECTORY = "$baseApi/scripts/directory"
    const val SCRIPTS_RENAME = "$baseApi/scripts/rename"
    const val SCRIPTS_MOVE = "$baseApi/scripts/move"
    const val SCRIPTS_COPY = "$baseApi/scripts/copy"
    const val SCRIPTS_BATCH = "$baseApi/scripts/batch"
    const val SCRIPTS_VERSIONS = "$baseApi/scripts/versions"
    const val SCRIPTS_RUN = "$baseApi/scripts/run"
    const val SCRIPTS_RUN_CODE = "$baseApi/scripts/run-code"
    const val SCRIPTS_RUN_LOGS = "$baseApi/scripts/run-logs"
    const val SCRIPTS_RUN_STOP = "$baseApi/scripts/run-stop"
    const val SCRIPTS_RUN_CLEAR = "$baseApi/scripts/run-clear"
    const val SCRIPTS_FORMAT = "$baseApi/scripts/format"

    // EnvVars
    const val ENVS = "$baseApi/envs"
    fun envById(id: Int): String = "$baseApi/envs/$id"
    fun envEnable(id: Int): String = "$baseApi/envs/$id/enable"
    fun envDisable(id: Int): String = "$baseApi/envs/$id/disable"
    fun envMoveTop(id: Int): String = "$baseApi/envs/$id/move-top"
    fun envCancelTop(id: Int): String = "$baseApi/envs/$id/cancel-top"
    const val ENVS_BATCH = "$baseApi/envs/batch"
    const val ENVS_GROUPS = "$baseApi/envs/groups"
    const val ENVS_EXPORT = "$baseApi/envs/export"
    const val ENVS_IMPORT = "$baseApi/envs/import"

    // Subscriptions
    const val SUBSCRIPTIONS = "$baseApi/subscriptions"
    fun subscriptionById(id: Int): String = "$baseApi/subscriptions/$id"
    fun subscriptionEnable(id: Int): String = "$baseApi/subscriptions/$id/enable"
    fun subscriptionDisable(id: Int): String = "$baseApi/subscriptions/$id/disable"
    fun subscriptionPull(id: Int): String = "$baseApi/subscriptions/$id/pull"
    fun subscriptionPullStop(id: Int): String = "$baseApi/subscriptions/$id/pull/stop"
    fun subscriptionPullStream(id: Int): String = "$baseApiV1/subscriptions/$id/pull-stream"
    fun subscriptionLogs(id: Int): String = "$baseApi/subscriptions/$id/logs"
    const val SUBSCRIPTIONS_BATCH_DELETE = "$baseApi/subscriptions/batch-delete"

    // Notifications
    const val NOTIFICATIONS = "$baseApi/notifications"
    fun notificationById(id: Int): String = "$baseApi/notifications/$id"
    fun notificationEnable(id: Int): String = "$baseApi/notifications/$id/enable"
    fun notificationDisable(id: Int): String = "$baseApi/notifications/$id/disable"
    fun notificationTest(id: Int): String = "$baseApi/notifications/$id/test"
    const val NOTIFICATIONS_TYPES = "$baseApi/notifications/types"
    const val NOTIFICATIONS_SEND = "$baseApi/notifications/send"

    // Dependencies
    const val DEPS = "$baseApi/deps"
    fun depById(id: Int): String = "$baseApi/deps/$id"
    fun depStatus(id: Int): String = "$baseApi/deps/$id/status"
    fun depReinstall(id: Int): String = "$baseApi/deps/$id/reinstall"
    fun depCancel(id: Int): String = "$baseApi/deps/$id/cancel"
    fun depLogStream(id: Int): String = "$baseApiV1/deps/$id/log-stream"
    const val DEPS_BATCH_DELETE = "$baseApi/deps/batch-delete"
    const val DEPS_PIP = "$baseApi/deps/pip"
    const val DEPS_NPM = "$baseApi/deps/npm"
    const val DEPS_MIRRORS = "$baseApi/deps/mirrors"
    const val DEPS_PYTHON_RUNTIMES = "$baseApi/deps/python-runtimes"
    const val DEPS_PYTHON_RUNTIME_DEFAULT = "$baseApi/deps/python-runtime-default"

    // Users
    const val USERS = "$baseApi/users"
    fun userById(id: Int): String = "$baseApi/users/$id"
    fun userResetPassword(id: Int): String = "$baseApi/users/$id/reset-password"

    // Security
    const val SECURITY = "$baseApi/security"
    const val SECURITY_LOGIN_LOGS = "$baseApi/security/login-logs"
    const val SECURITY_SESSIONS = "$baseApi/security/sessions"
    const val SECURITY_SESSIONS_OTHERS = "$baseApi/security/sessions/others"
    fun sessionById(id: Int): String = "$baseApi/security/sessions/$id"
    const val SECURITY_IP_WHITELIST = "$baseApi/security/ip-whitelist"
    fun ipWhitelistById(id: Int): String = "$baseApi/security/ip-whitelist/$id"
    const val SECURITY_AUDIT_LOGS = "$baseApi/security/audit-logs"
    const val SECURITY_LOGIN_STATS = "$baseApi/security/login-stats"
    const val SECURITY_2FA_SETUP = "$baseApi/security/2fa/setup"
    const val SECURITY_2FA_VERIFY = "$baseApi/security/2fa/verify"
    const val SECURITY_2FA = "$baseApi/security/2fa"
    const val SECURITY_2FA_STATUS = "$baseApi/security/2fa/status"

    // Configs
    const val CONFIGS = "$baseApi/configs"
    fun configByKey(key: String): String = "$baseApi/configs/$key"
    const val CONFIGS_BATCH = "$baseApi/configs/batch"

    // SSH Keys
    const val SSH_KEYS = "$baseApi/ssh-keys"
    fun sshKeyById(id: Int): String = "$baseApi/ssh-keys/$id"

    // Open API
    const val OPENAPI = "$baseApi/openapi"
    const val OPENAPI_TOKEN = "$baseApi/openapi/token"
    const val OPENAPI_APPS = "$baseApi/open-api/apps"
    fun openApiAppById(id: Int): String = "$baseApi/open-api/apps/$id"
    fun openApiAppEnable(id: Int): String = "$baseApi/open-api/apps/$id/enable"
    fun openApiAppDisable(id: Int): String = "$baseApi/open-api/apps/$id/disable"
    fun openApiAppResetSecret(id: Int): String = "$baseApi/open-api/apps/$id/reset-secret"
    fun openApiAppViewSecret(id: Int): String = "$baseApi/open-api/apps/$id/view-secret"
    fun openApiAppLogs(id: Int): String = "$baseApi/open-api/apps/$id/logs"
}
